### PR TITLE
Added an improved demo app experience

### PR DESCRIPTION
**Pull request by juwara0**
# feature

---

This change is [Reviewable](https://reviewable.io/reviews/ciena-blueplanet/ember-block-slots/10)

### CODE REVIEW

**Comment by job13er** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[tests/dummy/app/pods/components/default-slot-yield/component.js, line 7 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFf9SpuZ3KA4YXaL8ko:-KFf9SpuZ3KA4YXaL8kp:242471274) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/components/default-slot-yield/component.js#L7)):_
This looks strikingly similar to the contents of `tests/dummy/app/pods/components/all-slot-yields/component.js` If the contents of one is supposed to override the contents of the other, we should probably make them different in the demo to highlight that fact. Or, if I'm way off, please show me the error of my ways and explain what these are ;)

Or are they just two separate situations you're demoing, and have nothing to do with one another? If that's the case, why do we need two copies?

---

_[tests/dummy/app/pods/demo/template.hbs, line 30 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfAtVL92yc3Qk78mAZ:-KFfAtVMRfza_TDSobUb:650834994) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/demo/template.hbs#L30)):_
I can't wait until we find an alternative to this where you can actually just reference the contents of a template instead of having to duplicate it's contents. 

---

_[tests/dummy/app/styles/_colors.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfB3_1kEqhogtyZlzz:-KFfB3_1kEqhogtyZm--:-1963224556) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_colors.scss#L1)):_
Why do we need to duplicate these instead of pulling them from `ember-frost-core`?

---

_[tests/dummy/app/styles/_flex.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBE5DVa39MeAOdYyR:-KFfBE5DVa39MeAOdYyS:1645259919) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_flex.scss#L1)):_
Same comment as `_colors.scss`, why is this `ember-frost-core` code being duplicated here?

---

_[tests/dummy/app/styles/_normalize.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBJ4NAU_KKEQ7kqNp:-KFfBJ4NAU_KKEQ7kqNq:1645259919) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_normalize.scss#L1)):_
Same comment as `_colors.scss`, why is this `ember-frost-core` code being duplicated here?

---

_[tests/dummy/app/styles/_typography.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBMPanfLmMN53czQY:-KFfBMPanfLmMN53czQZ:1645259919) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_typography.scss#L1)):_
Same comment as `_colors.scss`, why is this `ember-frost-core` code being duplicated here?

---

_[tests/dummy/app/styles/app.scss, line 11 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBeAKIzBDDduAmEPJ:-KFfBeAKIzBDDduAmEPK:-232506030) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/app.scss#L11)):_
Inconsistent indentation. Maybe turn on `sass-lint`? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10)_

**Comment by juwara0** [comment]
Review status: 14 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

_[tests/dummy/app/pods/components/default-slot-yield/component.js, line 7 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFf9SpuZ3KA4YXaL8ko:-KFfCRir12jeO9qok03V:243927511) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/components/default-slot-yield/component.js#L7)):_
What I am attempting to demonstrate is two different behaviors of this nested component given the same data set but differences in the way the component is utilized. This was setup in the PODS configuration with a Component acting as the Controller for the data so I followed the existing pattern and setup the data for the other component the same way.

---

_[tests/dummy/app/pods/demo/template.hbs, line 30 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfAtVL92yc3Qk78mAZ:-KFfETXsNaPrNhOYy8z5:-1530771663) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/demo/template.hbs#L30)):_
Agreed.

---

_[tests/dummy/app/styles/_colors.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfB3_1kEqhogtyZlzz:-KFfF-GYQxtLCuD6BplL:-890173499) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_colors.scss#L1)):_
I am just using this for styling of the demo app. I do not want to pull in `ember-frost-core` just for that.

---

_[tests/dummy/app/styles/_flex.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBE5DVa39MeAOdYyR:-KFfFQ7aHpKQJAC2ayBg:-890173499) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_flex.scss#L1)):_
I am just using this for styling of the demo app. I do not want to pull in `ember-frost-core` just for that.

---

_[tests/dummy/app/styles/_normalize.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBJ4NAU_KKEQ7kqNp:-KFfFRvaiGUPNauTKecM:-890173499) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_normalize.scss#L1)):_
I am just using this for styling of the demo app. I do not want to pull in `ember-frost-core` just for that.

---

_[tests/dummy/app/styles/_typography.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBMPanfLmMN53czQY:-KFfFSw4FnO1Z8EQDIwm:-890173499) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_typography.scss#L1)):_
I am just using this for styling of the demo app. I do not want to pull in `ember-frost-core` just for that.

---

_[tests/dummy/app/styles/app.scss, line 11 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBeAKIzBDDduAmEPJ:-KFfH04vEvslsL3H5jA_:-499146009) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/app.scss#L11)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10)_

**Comment by job13er** [comment]
Review status: 14 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

_[tests/dummy/app/pods/components/default-slot-yield/component.js, line 7 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFf9SpuZ3KA4YXaL8ko:-KFfISxo1WEGdzHWxARR:-622541853) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/components/default-slot-yield/component.js#L7)):_
I'm sorry, I guess I'm still not quite following why we need two components that do exactly the same thing? Even in the demo. Could you re-use the other one? Or have this one have different values maybe? It just seems wrong to have two identical files, doesn't it? 

---

_[tests/dummy/app/styles/_colors.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfB3_1kEqhogtyZlzz:-KFfId7W8yZgnaHOQVdz:-271661080) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_colors.scss#L1)):_
Isn't that kinda the point of `ember-frost-core`? Couldn't you pull it in to `devDependencies` and only use it for the dummy app? I won't add the same question to all the other comments ;)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10)_

**Comment by juwara0** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_[tests/dummy/app/pods/components/default-slot-yield/component.js, line 7 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFf9SpuZ3KA4YXaL8ko:-KFivn2BNtvHuovhLBDL:-737252830) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/pods/components/default-slot-yield/component.js#L7)):_
I have cleaned this up. It is now one component and one data file.

---

_[tests/dummy/app/styles/_colors.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfB3_1kEqhogtyZlzz:-KFivkjilogfmVyVuerA:-791163841) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_colors.scss#L1)):_
This has been removed. I am now importing this from `ember-frost-core`.

---

_[tests/dummy/app/styles/_flex.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBE5DVa39MeAOdYyR:-KFivioj-CLFYy2P8BYl:-791163841) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_flex.scss#L1)):_
This has been removed. I am now importing this from `ember-frost-core`.

---

_[tests/dummy/app/styles/_typography.scss, line 1 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10#-KFfBMPanfLmMN53czQY:-KFivXLT5NFLyhT7g6bq:-791163841) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/947d4e77b780c68506e3ec4c6ae6c475d29a1bd9/tests/dummy/app/styles/_typography.scss#L1)):_
This has been removed. I am now importing this from `ember-frost-core`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10)_

**Comment by job13er** [comment]
Reviewed 1 of 1 files at r2, 13 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/10)_

**Pull request merged**
