### PR TITLE
moved _slot property and _registerSlot method to an extension of Component

### PR DESCRIPTION
**Pull request by juwara0**
# feature

---

This change is [Reviewable](https://reviewable.io/reviews/ciena-blueplanet/ember-block-slots/4)

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[tests/unit/initializers/component-block-slots-test.js, line 28 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/4#-KDP8ApwRW8xvSMvpStA:-KDP8ApwRW8xvSMvpStB:460437361) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/c72cb10c0d08068302e963bf684fa8a7d4c7186a/tests/unit/initializers/component-block-slots-test.js#L28)):_
Can we add a component test as well to demonstrate that the expected variables are available on a new component?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/4)_

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-block-slots/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-block-slots)

**Comment by sglanzer-fire** [comment]
@juwara0 the linting is failing - if you run `npm run lint ___ --fix` for those directories it should clean up most of it and then you can run `npm run lint` to check for any remaining issues

**Comment by juwara0** [comment]
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[tests/unit/initializers/component-block-slots-test.js, line 28 [r1]](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/4#-KDP8ApwRW8xvSMvpStA:-KDTdeLlNbc0IWkrTJoF:-499146009) ([raw file](https://github.com/ciena-blueplanet/ember-block-slots/blob/c72cb10c0d08068302e963bf684fa8a7d4c7186a/tests/unit/initializers/component-block-slots-test.js#L28)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/4)_

**Comment by sglanzer-fire** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ciena-blueplanet/ember-block-slots/4)_

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-block-slots/pull-request/4/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-block-slots)

**Pull request merged**
