### PR TITLE
Upgrade ember-prop-types dependency

### PR DESCRIPTION
**Pull request by dfreeman**
We lint to enforce a single version of any non-build-tooling addons in our apps, and we're aiming to upgrade our version of ember-prop-types, but this addon's dependency is currently locked to 2.x. It doesn't appear any code changes are needed here for 3.x compatibility, but given that most of the tests are pended, I'm not 100% confident :)

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

Expand ember-prop-types dependency range and remove unnecessary installation blueprint.

---
This change is [Reviewable](https://reviewable.io/reviews/ciena-blueplanet/ember-block-slots/48)

### CODE REVIEW

**Comment by sglanzer** [comment]
Approved - thanks 👍

**Comment by sglanzer-fire** [comment]
@dfreeman the blueprint still has 2.x https://github.com/ciena-blueplanet/ember-block-slots/blob/master/blueprints/ember-block-slots/index.js#L8, but there really shouldn't be a blueprint install for this - would you mind removing it?

@sandersky @job13er I know we had discussed the idea that consumption of a downstream #major# means a #major# - I assume this would still be the case even without blueprints because any consumers would potentially have a version conflict that crossed major releases.  Assuming that all makes sense this would be a #major#

**Comment by sandersky** [comment]
@sglanzer looking at the implementation of this addon I noticed it doesn't use `getDefaultProps()` which is the only reason for the `ember-prop-types` 3.x major. Since this addon appears to have it listed as a dependency why not just make the version `>=2.0.0 <4.0.0`. This will allow users to get `ember-prop-types` 3 while still being able to use 2.x if need be. If a consumer has 2.x installed directly that should satisfy the range on this addon keeping an extra nested copy from being installed.

**Comment by dfreeman** [comment]
@sglanzer I hadn't even noticed the blueprint, so thanks for calling that out—I'll remove it.
@sandersky `>=2.0.0 <4.0.0` seems reasonable to me

**Comment by sandersky** [comment]
I personally hate having the `dependencies` and prefer just to have the blueprints. My reasoning is with Ember only one version a dependency makes it into your build regardless of how many different versions addons try to bring in. With that being said one addon could list `ember-prop-types` 2.x as a dependency and another `ember-prop-types` 3.x as a dependency. Either 2.x or 3.x will actually end up in your app build at it won't be obvious which one. If one of your addons is leveraging a new feature in 3.x then you'll have potential issues without even realizing it. Using blueprints insteand allows you as an app developer to explicitly specify which version you want and not worry about nested dependencies at all. Of course you could still specify 2.x and an addon relies on 3.x, but at that point I think you'd be responsible for making sure your addons play nice together, which arguably should be caught by tests because everyone should be writing adequate tests for their apps/addons. I think this dependency vs blueprint debate keeps popping up though in different circles and I've yet to hear a clear winner in any of them I know the `ember-redux` team is now using the blueprint approach and Ciena has for the most part followed that, although as of lately I've been seeing more `dependencies` being defined. @sglanzer I'd really like to nail this down to one or the other and make sure all addons we work on are adhering to it.

**Comment by dfreeman** [comment]
As a non-Ciena person my opinion obviously isn't key here, but since I'm on the thread anyway I'll weigh in with some observations that have led us to avoid the blueprint approach in our addons:
 - When an addon's acceptable version range for a transitive dependency changes, you have to rely on users to re-run the blueprint the next time they upgrade their copy of that addon. Some will do this, but in my personal experience a lot of people won't, no matter how big and bold the text in the README and CHANGELOG is telling them to do it.
 - As folks start to migrate to Yarn, we're in a (hopefully) transient period where `ember install` is being used less, which means some people may not execute the blueprint at all. Granted, users should understand what they're taking on by using not-yet-supported tooling, but that doesn't mean it actually happens ;)

Because of those points, we've been using `dependencies` in both our public and internal addons, and that's why we introduced the (currently private) dependency linting addon I mentioned in the issue description. It crawls the full tree of activated addons at build time to ensure that only one version (or a configured acceptable combination) will actually end up in the final build, regardless of what approach the addon authors chose to include those dependencies.

**Comment by sandersky** [comment]
@dfreeman when you say currently private, are there plans to open source this? It sounds like a very useful tool to have in the open source community and if provided would mean addons like this could encompass it as part of the CI to ensure everything is playing ball at all layers.

**Comment by dfreeman** [comment]
For sure. The plan was to try it out internally to make sure it was actually a viable approach before opening it up, but it's had a bit of burn in now and so far things have been reasonable.

I'm out of pocket the rest of the day today unfortunately, but should have a chance to pursue opening it up further tomorrow or Friday.

**Comment by sglanzer-fire** [comment]
Approved - nice discussion and thanks for the PR!

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-block-slots/pull-request/48/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-block-slots)

**Comment by sglanzer-fire** [comment]
@sandersky we can discuss more over Slack, but I posted an approach to this a few weeks back that I think we should be taking in general

1.  If the dependency has no blueprints -> use dependencies
2.  If the dependency runs a blueprint -> blueprints
3.  If you update a blueprint based dependency -> yell in as many forms as possible (README, CHANGELOG, Slack, etc.)

I believe there are *far* less addons that require blueprints to be run than we currently have in our blueprints and I believe this would go, let's say, 80% of the way in addressing some of our consumers dependency issues.

Promoting the usage of the ecosystem installer would also be a good approach to solve this - probably worth discussing this with you since you're always a good champion :)

**Comment by dfreeman** [comment]
Finally got around to publishing that addon I mentioned, if it's of any interest to y'all: https://github.com/salsify/ember-cli-dependency-lint

**Pull request merged**
